#!/usr/bin/perl

use strict;
use warnings;
use Cwd;
use File::Basename;
use IPC::Open2;

# The known Perl modules
my @kiwiModules = qw (KIWIArchList.pm KIWIArch.pm KIWIBoot.pm KIWICache.pm
					KIWICollect.pm KIWICommandLine.pm KIWIConfigure.pm
					KIWIGlobals.pm KIWIImageCreator.pm KIWIImageFormat.pm
					KIWIImage.pm KIWIIsoLinux.pm KIWILocator.pm
					KIWILog.pm KIWIManager.pm KIWIMigrate.pm KIWIOverlay.pm
					KIWIProductData.pm KIWIQX.pm KIWIRepoMetaHandler.pm
					KIWIRoot.pm KIWIRuntimeChecker.pm
					KIWISatSolver.pm KIWISharedMem.pm KIWISocket.pm
					KIWIURL.pm KIWIUtil.pm KIWIXML.pm KIWIXMLDataBase.pm
					KIWIXMLDescriptionData.pm KIWIXMLDriverData.pm
					KIWIXMLEC2ConfigData.pm KIWIXMLFileData.pm KIWIXMLInfo.pm
					KIWIXMLOEMConfigData.pm KIWIXMLPXEDeployData.pm
					KIWIXMLPreferenceData.pm KIWIXMLProfileData.pm
					KIWIXMLRepositoryData.pm KIWIXMLSplitData.pm
					KIWIXMLSystemdiskData.pm KIWIXMLTypeData.pm
					KIWIXMLVMachineData.pm	KIWIXMLValidator.pm
					KIWICommandLine.t KIWIImageCreator.t
					KIWILocator.t KIWIRuntimeChecker.t KIWIXML.t
					KIWIXMLDescriptionData.t KIWIXMLDriverData.t
					KIWIXMLEC2ConfigData.t KIWIXMLFileData.t KIWIXMLInfo.t
					KIWIXMLOEMConfigData.t KIWIXMLPXEDeployData.t
					KIWIXMLPreferenceData.t KIWIXMLProfileData.t
					KIWIXMLRepositoryData.t KIWIXMLSplitData.t
					KIWIXMLSystemdiskData.t KIWIXMLTypeData.t
					KIWIXMLVMachineData.t
					KIWIXMLValidator.t ktLog.pm ktTestCase.pm
					kiwiCommandLine.pm kiwiLocator.pm kiwiImageCreator.pm
					kiwiRuntimeChecker.pm kiwiXML.pm
					kiwiXMLDescriptionData.pm kiwiXMLDriverData.pm
					kiwiXMLEC2ConfigData.pm kiwiXMLFileData.pm kiwiXMLInfo.pm
					kiwiXMLOEMConfigData.pm kiwiXMLPXEDeployData.pm
					kiwiXMLPreferenceData.pm kiwiXMLProfileData.pm
					kiwiXMLRepositoryData.pm kiwiXMLSplitData.pm
					kiwiXMLSystemdiskData.pm kiwiXMLTypeData.pm
					kiwiXMLVMachineData.pm
					kiwiXMLValidator.pm collector.pl);

# List of modules not clean to level 1 (brutal) of perlcritic
my @notClean1 = qw (KIWIArchList.pm KIWIArch.pm KIWIBoot.pm KIWICache.pm
					KIWICollect.pm KIWICommandLine.pm KIWIConfigure.pm
					KIWIGlobals.pm KIWIImageCreator.pm KIWIImageFormat.pm
					KIWIImage.pm KIWIIsoLinux.pm KIWILocator.pm
					KIWILog.pm KIWIManager.pm KIWIMigrate.pm KIWIOverlay.pm
					KIWIProductData.pm KIWIQX.pm KIWIRepoMetaHandler.pm
					KIWIRoot.pm KIWIRuntimeChecker.pm
					KIWISatSolver.pm KIWISharedMem.pm KIWISocket.pm
					KIWIURL.pm KIWIUtil.pm KIWIXML.pm KIWIXMLDataBase.pm
					KIWIXMLDescriptionData.pm KIWIXMLDriverData.pm
					KIWIXMLEC2ConfigData.pm KIWIXMLFileData.pm KIWIXMLInfo.pm
					KIWIXMLOEMConfigData.pm KIWIXMLPXEDeployData.pm
					KIWIXMLPreferenceData.pm KIWIXMLProfileData.pm
					KIWIXMLRepositoryData.pm KIWIXMLSplitData.pm
					KIWIXMLSystemdiskData.pm KIWIXMLTypeData.pm
					KIWIXMLVMachineData.pm KIWIXMLValidator.pm
					KIWICommandLine.t KIWIImageCreator.t
					KIWILocator.t KIWIRuntimeChecker.t KIWIXML.t
					KIWIXMLDescriptionData.t KIWIXMLDriverData.t
					KIWIXMLEC2ConfigData.t KIWIXMLFileData.t KIWIXMLInfo.t
					KIWIXMLOEMConfigData.t KIWIXMLPXEDeployData.t
					KIWIXMLPreferenceData.t KIWIXMLProfileData.t
					KIWIXMLRepositoryData.t KIWIXMLSplitData.t
					KIWIXMLSystemdiskData.t KIWIXMLTypeData.t
					KIWIXMLVMachineData.t
					KIWIXMLValidator.t ktLog.pm ktTestCase.pm
					kiwiCommandLine.pm kiwiLocator.pm kiwiImageCreator.pm
					kiwiRuntimeChecker.pm kiwiXML.pm
					kiwiXMLDescriptionData.pm kiwiXMLDriverData.pm
					kiwiXMLEC2ConfigData.pm kiwiXMLFileData.pm kiwiXMLInfo.pm
					kiwiXMLOEMConfigData.pm kiwiXMLPXEDeployData.pm
					kiwiXMLPreferenceData.pm kiwiXMLProfileData.pm
					kiwiXMLRepositoryData.pm kiwiXMLSplitData.pm
					kiwiXMLSystemdiskData.pm kiwiXMLTypeData.pm
					kiwiXMLVMachineData.pm
					kiwiXMLValidator.pm collector.pl);

# List of modules not clean to level 2 (cruel) of perlcritic
my @notClean2 = qw (KIWIArchList.pm KIWIArch.pm KIWIBoot.pm KIWICache.pm
					KIWICollect.pm KIWICommandLine.pm KIWIConfigure.pm
					KIWIGlobals.pm KIWIImageCreator.pm KIWIImageFormat.pm
					KIWIImage.pm KIWIIsoLinux.pm KIWILocator.pm
					KIWILog.pm KIWIManager.pm KIWIMigrate.pm KIWIOverlay.pm
					KIWIProductData.pm KIWIQX.pm KIWIRepoMetaHandler.pm
					KIWIRoot.pm KIWIRuntimeChecker.pm
					KIWISatSolver.pm KIWISharedMem.pm KIWISocket.pm
					KIWIURL.pm KIWIUtil.pm KIWIXML.pm KIWIXMLDataBase.pm
					KIWIXMLDescriptionData.pm KIWIXMLDriverData.pm
					KIWIXMLFileData.pm KIWIXMLInfo.pm KIWIXMLOEMConfigData.pm
					KIWIXMLRepositoryData.pm KIWIXMLTypeData.pm
					KIWIXMLValidator.pm
					KIWICommandLine.t KIWIImageCreator.t
					KIWILocator.t KIWIRuntimeChecker.t KIWIXML.t
					KIWIXMLDescriptionData.t KIWIXMLDriverData.t
					KIWIXMLEC2ConfigData.t KIWIXMLFileData.t KIWIXMLInfo.t
					KIWIXMLOEMConfigData.t KIWIXMLPXEDeployData.t
					KIWIXMLPreferenceData.t KIWIXMLProfileData.t
					KIWIXMLRepositoryData.t KIWIXMLSplitData.t
					KIWIXMLSystemdiskData.t KIWIXMLTypeData.t
					KIWIXMLVMachineData.t
					KIWIXMLValidator.t ktTestCase.pm
					kiwiCommandLine.pm kiwiLocator.pm kiwiImageCreator.pm
					kiwiRuntimeChecker.pm kiwiXML.pm kiwiXMLInfo.pm
					kiwiXMLSystemdiskData.pm kiwiXMLVMachineData.pm
					kiwiXMLValidator.pm collector.pl);

# List of modules not clean to level 3 (harsh) of perlcritic
my @notClean3 = qw (KIWIArchList.pm KIWIArch.pm KIWIBoot.pm KIWICache.pm
					KIWICollect.pm KIWICommandLine.pm KIWIConfigure.pm
					KIWIGlobals.pm KIWIImageCreator.pm KIWIImageFormat.pm
					KIWIImage.pm KIWIIsoLinux.pm
					KIWILog.pm KIWIManager.pm KIWIMigrate.pm KIWIOverlay.pm
					KIWIProductData.pm KIWIQX.pm KIWIRepoMetaHandler.pm
					KIWIRoot.pm KIWIRuntimeChecker.pm
					KIWISatSolver.pm KIWISharedMem.pm KIWISocket.pm
					KIWIURL.pm KIWIUtil.pm KIWIXML.pm KIWIXMLDataBase.pm
					KIWIXMLInfo.pm
					KIWIXMLRepositoryData.pm KIWIXMLValidator.pm
					KIWICommandLine.t KIWIImageCreator.t
					KIWILocator.t KIWIRuntimeChecker.t KIWIXML.t
					KIWIXMLDescriptionData.t KIWIXMLDriverData.t
					KIWIXMLEC2ConfigData.t KIWIXMLFileData.t KIWIXMLInfo.t
					KIWIXMLOEMConfigData.t KIWIXMLPXEDeployData.t
					KIWIXMLPreferenceData.t KIWIXMLProfileData.t
					KIWIXMLRepositoryData.t KIWIXMLSplitData.t
					KIWIXMLSystemdiskData.t KIWIXMLTypeData.t
					KIWIXMLVMachineData.t
					KIWIXMLValidator.t kiwiCommandLine.pm kiwiLocator.pm
					kiwiImageCreator.pm kiwiRuntimeChecker.pm kiwiXML.pm
					kiwiXMLInfo.pm kiwiXMLValidator.pm collector.pl);

# List of modules not clean to level 4 (stern) of perlcritic
my @notClean4 = qw (KIWIArchList.pm KIWIArch.pm KIWIBoot.pm
					KIWICollect.pm KIWIConfigure.pm
					KIWIImageFormat.pm KIWIImage.pm
					KIWILog.pm KIWIManager.pm KIWIMigrate.pm
					KIWIProductData.pm KIWIRepoMetaHandler.pm
					KIWIRoot.pm KIWISatSolver.pm KIWISharedMem.pm
					KIWIXML.pm
					KIWICommandLine.t KIWIImageCreator.t
					KIWILocator.t KIWIRuntimeChecker.t KIWIXML.t
					KIWIXMLDescriptionData.t KIWIXMLDriverData.t
					KIWIXMLEC2ConfigData.t KIWIXMLFileData.t KIWIXMLInfo.t
					KIWIXMLOEMConfigData.t KIWIXMLPXEDeployData.t
					KIWIXMLPreferenceData.t KIWIXMLProfileData.t
					KIWIXMLRepositoryData.t KIWIXMLSplitData.t
					KIWIXMLSystemdiskData.t KIWIXMLTypeData.t
					KIWIXMLVMachineData.t
					collector.pl);

# List of modules not clean to level 5 (gentel) of perlcritic
my @notClean5 = qw (KIWIArchList.pm KIWIBoot.pm);

my ($chld_in, $chld_out);
my $pid = open2(
	$chld_out, $chld_in, 'git', 'diff-index', '--name-only','HEAD'
);
waitpid( $pid, 0 );

my @changedFiles;
# Collect all changed Perl code and verify that all Perl modules are known
while (<$chld_out>) {
	my $fname = basename($_);
	chomp $fname;
	if ($fname =~ /.*\.pm$|\.pl$|\.t$/x) {
		push @changedFiles, $_;
		if (! grep { /^$fname$/x } @kiwiModules) {
			print "Comitting new module '$fname'. Registration required. Add ";
			print "your module to the\ngit_hooks/pre-commit file in the ";
			print '@kiwiModules list as well as the notCleanX list';
			print "\n";
			exit 1;
		}
	}
}

# Make sure the perl code at least compiles
# Should the code layout in our repository change,
# these definitions have to be updated
my $modulesDir = getcwd() . '/modules';
my $testInclDir = getcwd() . '/tests/unit/lib';
my $pathEnv = "$modulesDir:$testInclDir";

my @failedToBuild;
for my $path (@changedFiles) {
	my $result = system "env PERL5LIB=$pathEnv perl -wc $path";
	if ($result != 0) {
		push @failedToBuild, $path;
	}
	if (scalar @failedToBuild) {
		print {*STDERR} 'Build failure detected for the following files:';
		for my $fl (@failedToBuild) {
			print {*STDERR} "\t$fl";
		}
		exit 1;
	}
}

my @criticLevelFiles = (\@notClean1, \@notClean2, \@notClean3, \@notClean4,
						\@notClean5);

# Verify the changed file against the strictest perlcritic level possible
# for this file based on the known "goodness" level. Default is level 3, the
# default is applied to perl code that is registerd, but not in any of the
# notClean arrays.
my $defSeverity = 3;
VERIFY:
for my $path (@changedFiles) {
	my $listed;
	for my $level (0..4) {
		my $fname = basename($path);
		if (! grep { /^$fname$/x } @{ $criticLevelFiles[$level] } ) {
			my $severity = int $level + 1;
			my $cmd = "perlcritic --quiet --severity $severity $path";
			my $status = system $cmd;
			if ($status) {
				print STDOUT "Failed verification for: $path\n";
				exit 1;
			}
			next VERIFY;
		} elsif (grep { /^$fname$/x } @{ $criticLevelFiles[$level] } ) {
			$listed = 1;
		}
	}
	if (! $listed) {
		my $cmd = "perlcritic --quiet --severity $defSeverity $path";
		my $status = system $cmd;
		if ($status) {
			print STDOUT "Failed verification for: $path\n";
			exit 1;
		}
	}
}

# Run tests as needed
my $cmd = './tests/runTests';
for my $path (@changedFiles) {
	chomp $path;
	$cmd .= " $path";
}

my $status = system $cmd;
if ($status) {
	exit 1;
}
