#!/usr/bin/perl

use strict;
use warnings;
use Cwd;
use File::Basename;
use IPC::Open2;

# The known Perl modules
my @kiwiModules = qw (
	KIWIArchList.pm
	KIWIArch.pm
	KIWIBasePlugin.pm
	KIWIBoot.pm
	KIWICache.pm
	KIWICollect.pm
	KIWICommandLine.pm
	KIWIConfigure.pm
	KIWIConfigWriter.pm
	KIWIConfigWriterFactory.pm
	KIWIContainerBuilder.pm
	KIWIContainerConfigWriter.pm
	KIWIContentPlugin.pm
	KIWIDescrPlugin.pm
	KIWIEulaPlugin.pm
	KIWIGlobals.pm
	KIWIImageBuilderBase.pm
	KIWIImageBuildFactory.pm
	KIWIImageCreator.pm
	KIWIImageFormat.pm
	KIWIImage.pm
	KIWIIsoLinux.pm
	KIWILiveTreePlugin.pm
	KIWILocator.pm
	KIWILog.pm
	KIWIManager.pm
	KIWIManagerApt.pm
	KIWIManagerSmart.pm
	KIWIManagerYum.pm
	KIWIManagerZypper.pm
	KIWIManagerEnsconce.pm
	KIWIMigrate.pm
	KIWIMiniIsoPlugin.pm
	KIWIOverlay.pm
	KIWIPatternsPlugin.pm
	KIWIProductData.pm
	KIWIQX.pm
	KIWIRepoMetaHandler.pm
	KIWIRoot.pm
	KIWIRuntimeChecker.pm
	KIWISatSolver.pm
	KIWISharedMem.pm
	KIWISocket.pm
	KIWITrace.pm
	KIWIURL.pm
	KIWIUtil.pm
	KIWIXML.pm
	KIWIXMLDataBase.pm
	KIWIXMLDescriptionData.pm
	KIWIXMLDriverData.pm
	KIWIXMLEC2ConfigData.pm
	KIWIXMLExceptData.pm
	KIWIXMLFileData.pm
	KIWIXMLInfo.pm
	KIWIXMLInstRepositoryData.pm
	KIWIXMLOEMConfigData.pm
	KIWIXMLPXEDeployConfigData.pm
	KIWIXMLPXEDeployData.pm
	KIWIXMLPackageArchiveData.pm
	KIWIXMLPackageCollectData.pm
	KIWIXMLPackageData.pm
	KIWIXMLPackageIgnoreData.pm
	KIWIXMLPackageProductData.pm
	KIWIXMLPreferenceData.pm
	KIWIXMLProductArchitectureData.pm
	KIWIXMLProductMetaChrootData.pm
	KIWIXMLProductMetaFileData.pm
	KIWIXMLProductOptionsData.pm
	KIWIXMLProductPackageData.pm
	KIWIXMLProfileData.pm
	KIWIXMLRepositoryBaseData.pm
	KIWIXMLRepositoryData.pm
	KIWIXMLSplitData.pm
	KIWIXMLStripData.pm
	KIWIXMLSystemdiskData.pm
	KIWIXMLTypeData.pm
	KIWIXMLUserData.pm
	KIWIXMLVMachineData.pm
	KIWIXMLValidator.pm
	KTCommandLine.t
	KTConfigWriterFactory.t
	KTContainerBuilder.t
	KTContainerConfigWriter.t
	KTImage.t
	KTImageBuilderBase.t
	KTImageBuildFactory.t
	KTImageCreator.t
	KTLocator.t
	KTRuntimeChecker.t
	KTXML.t
	KTXMLDescriptionData.t
	KTXMLDriverData.t
	KTXMLEC2ConfigData.t
	KTXMLExceptData.t
	KTXMLFileData.t
	KTXMLInfo.t
	KTXMLInstRepositoryData.t
	KTXMLOEMConfigData.t
	KTXMLPXEDeployConfigData.t
	KTXMLPXEDeployData.t
	KTXMLPackageArchiveData.t
	KTXMLPackageCollectData.t
	KTXMLPackageData.t
	KTXMLPackageIgnoreData.t
	KTXMLPackageProductData.t
	KTXMLPreferenceData.t
	KTXMLProductArchitectureData.t
	KTXMLProductMetaChrootData.t
	KTXMLProductMetaFileData.t
	KTXMLProductOptionsData.t
	KTXMLProductPackageData.t
	KTXMLProfileData.t
	KTXMLRepositoryData.t
	KTXMLSplitData.t
	KTXMLStripData.t
	KTXMLSystemdiskData.t
	KTXMLTypeData.t
	KTXMLUserData.t
	KTXMLVMachineData.t
	KTXMLValidator.t
	ktLog.pm
	ktTestCase.pm
	kiwiCommandLine.pm
	kiwiConfigWriterFactory.pm
	kiwiContainerBuilder.pm
	kiwiContainerConfigWriter.pm
	kiwiLocator.pm
	kiwiImage.pm
	kiwiImageBuilderBase.pm
	kiwiImageBuildFactory.pm
	kiwiImageCreator.pm
	kiwiRuntimeChecker.pm
	kiwiXML.pm
	kiwiXMLDescriptionData.pm
	kiwiXMLDriverData.pm
	kiwiXMLEC2ConfigData.pm
	kiwiXMLExceptData.pm
	kiwiXMLFileData.pm
	kiwiXMLInfo.pm
	kiwiXMLInstRepositoryData.pm
	kiwiXMLOEMConfigData.pm
	kiwiXMLPXEDeployConfigData.pm
	kiwiXMLPXEDeployData.pm
	kiwiXMLPackageArchiveData.pm
	kiwiXMLPackageCollectData.pm
	kiwiXMLPackageData.pm
	kiwiXMLPackageIgnoreData.pm
	kiwiXMLPackageProductData.pm
	kiwiXMLPreferenceData.pm
	kiwiXMLProductArchitectureData.pm
	kiwiXMLProductMetaChrootData.pm
	kiwiXMLProductMetaFileData.pm
	kiwiXMLProductOptionsData.pm
	kiwiXMLProductPackageData.pm
	kiwiXMLProfileData.pm
	kiwiXMLRepositoryData.pm
	kiwiXMLSplitData.pm
	kiwiXMLStripData.pm
	kiwiXMLSystemdiskData.pm
	kiwiXMLTypeData.pm
	kiwiXMLUserData.pm
	kiwiXMLVMachineData.pm
	kiwiXMLValidator.pm
	kiwi.pl
);

# List of modules not clean to level 1 (brutal) of perlcritic
my @notClean1 = qw (
	KIWIArchList.pm
	KIWIArch.pm
	KIWIBasePlugin.pm
	KIWIBoot.pm
	KIWICache.pm
	KIWICollect.pm
	KIWICommandLine.pm
	KIWIConfigure.pm
	KIWIConfigWriter.pm
	KIWIConfigWriterFactory.pm
	KIWIContainerBuilder.pm
	KIWIContainerConfigWriter.pm
	KIWIContentPlugin.pm
	KIWIDescrPlugin.pm
	KIWIEulaPlugin.pm
	KIWIGlobals.pm
	KIWIImageBuilderBase.pm
	KIWIImageBuildFactory.pm
	KIWIImageCreator.pm
	KIWIImageFormat.pm
	KIWIImage.pm
	KIWIIsoLinux.pm
	KIWILiveTreePlugin.pm
	KIWILocator.pm
	KIWILog.pm
	KIWIManager.pm
	KIWIManagerApt.pm
	KIWIManagerSmart.pm
	KIWIManagerYum.pm
	KIWIManagerZypper.pm
	KIWIManagerEnsconce.pm
	KIWIMigrate.pm
	KIWIMiniIsoPlugin.pm
	KIWIOverlay.pm
	KIWIPatternsPlugin.pm
	KIWIProductData.pm
	KIWIQX.pm
	KIWIRepoMetaHandler.pm
	KIWIRoot.pm
	KIWIRuntimeChecker.pm
	KIWISatSolver.pm
	KIWISharedMem.pm
	KIWISocket.pm
	KIWITrace.pm
	KIWIURL.pm
	KIWIUtil.pm
	KIWIXML.pm
	KIWIXMLDataBase.pm
	KIWIXMLDescriptionData.pm
	KIWIXMLDriverData.pm
	KIWIXMLEC2ConfigData.pm
	KIWIXMLExceptData.pm
	KIWIXMLFileData.pm
	KIWIXMLInfo.pm
	KIWIXMLInstRepositoryData.pm
	KIWIXMLOEMConfigData.pm
	KIWIXMLPXEDeployConfigData.pm
	KIWIXMLPXEDeployData.pm
	KIWIXMLPackageArchiveData.pm
	KIWIXMLPackageCollectData.pm
	KIWIXMLPackageData.pm
	KIWIXMLPackageIgnoreData.pm
	KIWIXMLPackageProductData.pm
	KIWIXMLPreferenceData.pm
	KIWIXMLProductArchitectureData.pm
	KIWIXMLProductMetaChrootData.pm
	KIWIXMLProductMetaFileData.pm
	KIWIXMLProductOptionsData.pm
	KIWIXMLProductPackageData.pm
	KIWIXMLProfileData.pm
	KIWIXMLRepositoryBaseData.pm
	KIWIXMLRepositoryData.pm
	KIWIXMLSplitData.pm
	KIWIXMLStripData.pm
	KIWIXMLSystemdiskData.pm
	KIWIXMLTypeData.pm
	KIWIXMLUserData.pm
	KIWIXMLVMachineData.pm
	KIWIXMLValidator.pm
	KTCommandLine.t
	KTConfigWriterFactory.t
	KTContainerBuilder.t
	KTContainerConfigWriter.t
	KTImage.t
	KTImageBuilderBase.t
	KTImageBuildFactory.t
	KTImageCreator.t
	KTLocator.t
	KTRuntimeChecker.t
	KTXML.t
	KTXMLDescriptionData.t
	KTXMLDriverData.t
	KTXMLEC2ConfigData.t
	KTXMLExceptData.t
	KTXMLFileData.t
	KTXMLInfo.t
	KTXMLInstRepositoryData.t
	KTXMLOEMConfigData.t
	KTXMLPXEDeployConfigData.t
	KTXMLPXEDeployData.t
	KTXMLPackageArchiveData.t
	KTXMLPackageCollectData.t
	KTXMLPackageData.t
	KTXMLPackageIgnoreData.t
	KTXMLPackageProductData.t
	KTXMLPreferenceData.t
	KTXMLProductArchitectureData.t
	KTXMLProductMetaChrootData.t
	KTXMLProductMetaFileData.t
	KTXMLProductOptionsData.t
	KTXMLProductPackageData.t
	KTXMLProfileData.t
	KTXMLRepositoryData.t
	KTXMLSplitData.t
	KTXMLStripData.t
	KTXMLSystemdiskData.t
	KTXMLTypeData.t
	KTXMLUserData.t
	KTXMLVMachineData.t
	KTXMLValidator.t
	ktLog.pm
	ktTestCase.pm
	kiwiCommandLine.pm
	kiwiConfigWriterFactory.pm
	kiwiContainerBuilder.pm
	kiwiContainerConfigWriter.pm
	kiwiLocator.pm
	kiwiImage.pm
	kiwiImageBuilderBase.pm
	kiwiImageBuildFactory.pm
	kiwiImageCreator.pm
	kiwiRuntimeChecker.pm
	kiwiXML.pm
	kiwiXMLDescriptionData.pm
	kiwiXMLDriverData.pm
	kiwiXMLEC2ConfigData.pm
	kiwiXMLExceptData.pm
	kiwiXMLFileData.pm
	kiwiXMLInfo.pm
	kiwiXMLInstRepositoryData.pm
	kiwiXMLOEMConfigData.pm
	kiwiXMLPXEDeployConfigData.pm
	kiwiXMLPXEDeployData.pm
	kiwiXMLPackageArchiveData.pm
	kiwiXMLPackageCollectData.pm
	kiwiXMLPackageData.pm
	kiwiXMLPackageIgnoreData.pm
	kiwiXMLPackageProductData.pm
	kiwiXMLPreferenceData.pm
	kiwiXMLProductArchitectureData.pm
	kiwiXMLProductMetaChrootData.pm
	kiwiXMLProductMetaFileData.pm
	kiwiXMLProductOptionsData.pm
	kiwiXMLProductPackageData.pm
	kiwiXMLProfileData.pm
	kiwiXMLRepositoryData.pm
	kiwiXMLSplitData.pm
	kiwiXMLStripData.pm
	kiwiXMLSystemdiskData.pm
	kiwiXMLTypeData.pm
	kiwiXMLUserData.pm
	kiwiXMLVMachineData.pm
	kiwiXMLValidator.pm
	kiwi.pl
);

# List of modules not clean to level 2 (cruel) of perlcritic
my @notClean2 = qw (
	KIWIArchList.pm
	KIWIArch.pm
	KIWIBasePlugin.pm
	KIWIBoot.pm
	KIWICache.pm
	KIWICollect.pm
	KIWICommandLine.pm
	KIWIConfigure.pm
	KIWIContainerBuilder.pm
	KIWIContentPlugin.pm
	KIWIDescrPlugin.pm
	KIWIEulaPlugin.pm
	KIWIGlobals.pm
	KIWIImageBuilderBase.pm
	KIWIImageCreator.pm
	KIWIImageFormat.pm
	KIWIImage.pm
	KIWIIsoLinux.pm
	KIWILiveTreePlugin.pm
	KIWILocator.pm
	KIWILog.pm
	KIWIManager.pm
	KIWIManagerApt.pm
	KIWIManagerSmart.pm
	KIWIManagerYum.pm
	KIWIManagerZypper.pm
	KIWIManagerEnsconce.pm
	KIWIMigrate.pm
	KIWIMiniIsoPlugin.pm
	KIWIOverlay.pm
	KIWIPatternsPlugin.pm
	KIWIProductData.pm
	KIWIQX.pm
	KIWIRepoMetaHandler.pm
	KIWIRoot.pm
	KIWIRuntimeChecker.pm
	KIWISatSolver.pm
	KIWISharedMem.pm
	KIWISocket.pm
	KIWITrace.pm
	KIWIURL.pm
	KIWIUtil.pm
	KIWIXML.pm
	KIWIXMLInfo.pm
	KIWIXMLTypeData.pm
	KIWIXMLValidator.pm
	ktTestCase.pm
	kiwiCommandLine.pm
	kiwiContainerBuilder.pm
	kiwiLocator.pm
	kiwiImageCreator.pm
	kiwiRuntimeChecker.pm
	kiwiXML.pm
	kiwiXMLInfo.pm
	kiwiXMLSystemdiskData.pm
	kiwiXMLVMachineData.pm
	kiwiXMLValidator.pm
	kiwi.pl
);

# List of modules not clean to level 3 (harsh) of perlcritic
my @notClean3 = qw (
	KIWIArchList.pm
	KIWIBasePlugin.pm
	KIWIBoot.pm
	KIWICache.pm
	KIWICollect.pm
	KIWICommandLine.pm
	KIWIContentPlugin.pm
	KIWIDescrPlugin.pm
	KIWIEulaPlugin.pm
	KIWIGlobals.pm
	KIWIImageCreator.pm
	KIWIImageFormat.pm
	KIWIImage.pm
	KIWIIsoLinux.pm
	KIWILiveTreePlugin.pm
	KIWILog.pm
	KIWIManager.pm
	KIWIManagerApt.pm
	KIWIManagerSmart.pm
	KIWIManagerYum.pm
	KIWIManagerZypper.pm
	KIWIManagerEnsconce.pm
	KIWIMigrate.pm
	KIWIMiniIsoPlugin.pm
	KIWIOverlay.pm
	KIWIPatternsPlugin.pm
	KIWIProductData.pm
	KIWIQX.pm
	KIWIRepoMetaHandler.pm
	KIWIRoot.pm
	KIWIRuntimeChecker.pm
	KIWISatSolver.pm
	KIWISharedMem.pm
	KIWISocket.pm
	KIWITrace.pm
	KIWIURL.pm
	KIWIUtil.pm
	KIWIXML.pm
	KIWIXMLInfo.pm
	KIWIXMLRepositoryData.pm
	KIWIXMLTypeData.pm
	KIWIXMLValidator.pm
	kiwiCommandLine.pm
	kiwiLocator.pm
	kiwiImageCreator.pm
	kiwiRuntimeChecker.pm
	kiwiXML.pm
	kiwiXMLInfo.pm
	kiwiXMLValidator.pm
	kiwi.pl
);

# List of modules not clean to level 4 (stern) of perlcritic
my @notClean4 = qw (
	KIWIBasePlugin.pm
	KIWIContentPlugin.pm
	KIWIDescrPlugin.pm
	KIWIEulaPlugin.pm
	KIWILiveTreePlugin.pm
	KIWIMiniIsoPlugin.pm
	KIWIPatternsPlugin.pm
);

# List of modules not clean to level 5 (gentle) of perlcritic
my @notClean5 = qw (
	KIWIBasePlugin.pm
	KIWIContentPlugin.pm
	KIWIDescrPlugin.pm
	KIWIEulaPlugin.pm
	KIWILiveTreePlugin.pm
	KIWIMiniIsoPlugin.pm
	KIWIPatternsPlugin.pm
);

my @changedFiles;
my %knownFiles = map { ($_ => 1) } @kiwiModules;
my $chld_in;
my $chld_out;
my $pid = open2(
	$chld_out, $chld_in, 'git', 'diff-index', '--name-only','HEAD'
);
waitpid( $pid, 0 );
# Collect all changed Perl code and verify that all Perl modules are known
while (<$chld_out>) {
	my $exists;
	chomp $_;
	if (-f $_) {
		$exists = 1;
	}
	my $fname = basename($_);
	if ($fname =~ /.*\.pm$|\.pl$|\.t$/x) {
		push @changedFiles, $_;
		if (! $knownFiles{$fname} && $exists) {
			print "Comitting new module '$fname'. Registration required. Add ";
			print "your module to the\ngit-hooks/pre-commit file in the ";
			print '@kiwiModules list as well as the notCleanX list';
			print "\n";
			exit 1;
		}
	}
}

# Make sure the perl code at least compiles
# Should the code layout in our repository change,
# these definitions have to be updated
my $modulesDir = getcwd() . '/modules';
# Just add one of the plugin directories, all contain the same files
# this needs some cleaning up TODO
my $pluginsDir = getcwd() . '/distribution/kiwi-instsource-plugins-SLE-11-SP2';
my $testInclDir = getcwd() . '/tests/unit/lib';
my $pathEnv = "$modulesDir:$testInclDir:$pluginsDir";

my @failedToBuild;
for my $path (@changedFiles) {
	if (! -f $path) {
		# File was renamed, but is still in the list delivered by git
		next;
	}
	my $result = system "env PERL5LIB=$pathEnv perl -wc $path";
	if ($result != 0) {
		push @failedToBuild, $path;
	}
	if (scalar @failedToBuild) {
		print {*STDERR} 'Build failure detected for the following files:';
		for my $fl (@failedToBuild) {
			print {*STDERR} "\t$fl";
		}
		exit 1;
	}
}

my @criticLevelFiles = (\@notClean1, \@notClean2, \@notClean3, \@notClean4,
						\@notClean5);

# Verify the changed file against the strictest perlcritic level possible
# for this file based on the known "goodness" level. Default is level 3, the
# default is applied to perl code that is registerd, but not in any of the
# notClean arrays.
my $defSeverity = 3;
VERIFY:
for my $path (@changedFiles) {
	if (! -f $path) {
		# File was renamed, but is still in the list delivered by git
		next;
	}
	my $listed;
	for my $level (0..4) {
		my $fname = basename($path);
		if (! grep { /^$fname$/x } @{ $criticLevelFiles[$level] } ) {
			my $severity = int $level + 1;
			my $cmd = "perlcritic --quiet --severity $severity $path";
			my $status = system $cmd;
			if ($status) {
				print STDOUT "Failed verification for: $path\n";
				exit 1;
			}
			next VERIFY;
		} elsif (grep { /^$fname$/x } @{ $criticLevelFiles[$level] } ) {
			$listed = 1;
		}
	}
	if (! $listed) {
		my $cmd = "perlcritic --quiet --severity $defSeverity $path";
		my $status = system $cmd;
		if ($status) {
			print STDOUT "Failed verification for: $path\n";
			exit 1;
		}
	}
}

# Run tests as needed
my $cmd = './tests/runTests';
for my $path (@changedFiles) {
	chomp $path;
	$cmd .= " $path";
}

my $status = system $cmd;
if ($status) {
	exit 1;
}
