#!/bin/bash

# Author   : Robert Schweikert
# License  : GPLv2
# Copyright: 2012 SUSE

export ONE_AUTH=/var/lib/one/.one/one_auth
/usr/bin/onedatastore create testVM.dsconf
/usr/bin/oneimage create testVM.one -d 1
# Give the system some time to copy the image file
sleep 15
/usr/bin/onevm create testVM.vmd
