#!/bin/bash

# Author   : Robert Schweikert
# License  : GPLv2
# Copyright: 2011 SUSE

export ONE_AUTH=/var/lib/one/.one/one_auth
/usr/bin/oneimage create testVM.one
# Give the system some time to copy the image file
sleep 15
/usr/bin/onevm create testVM.vmd
