#! /bin/sh
# Copyright (c) 1995-1998 SuSE GmbH Nuernberg, Germany.
#
# Author: ms@suse.de
#
# /etc/init.d/sound
#   and its symbolic  link
# /usr/sbin/rcsound
#
### BEGIN INIT INFO
# Provides:          sound
# Required-Start:    $time $network $syslog
# Required-Stop:
# Default-Start:     3 5
# Default-Stop:      0 1 2 4 6
# Description:       openSUSE build service worker
### END INIT INFO

. /etc/rc.status

# Determine the base and follow a runlevel link name.
base=${0##*/}
link=${base#*[SK][0-9][0-9]}

rc_reset
case "$1" in
    start)
		echo -n "Loading sound support"
		modprobe snd-via82xx
		rc_status -v
	;;
	stop)
		echo -n "NOT IMPLEMENTED "
	rc_status -v
	;;
	restart)
		echo -n "NOT IMPLEMENTED "
		## If first returns OK call the second, if first or
		## second command fails, set echo return value.
		#$0 stop &&  $0 start
		rc_status
	;;
	try-restart)
		$0 status
		if test $? = 0; then
			$0 restart
		else
			rc_reset        # Not running is not a failure.
		fi
		# Remember status and be quiet
		rc_status
	;;
	reload)
	;;
	status)
		echo  "NOT IMPLEMENTED"
		#rc_status -v
	;;
	*)
		echo "Usage: $0 {start|stop|status|try-restart|restart|reload}"
		exit 1
	;;
esac
rc_exit
