VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.provider "docker" do |d|
    # select docker box to use for this build, build boxes can be found in:
    # Virtualization:Appliances:Images e.g docker-box-13.1
    # in order to import a build box call e.g:
    # cat kiwi-docker-image.tar.xz | docker import - kiwi-build-box:new
    d.image = "kiwi-build-box:new"
    d.create_args = ["--privileged=true", "-i", "-t"]
    # start the sshd in foreground to keep the container in running state
    d.cmd = ["/usr/sbin/sshd", "-D"]
    d.has_ssh = true
  end
end
