'\" t
.\"     Title: kiwi::kiwirc
.\"    Author: Robert Schweikert <rschweikert (AT) novell.com>
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: Created: 06/29/2015
.\"    Manual: KIWI Manualpage
.\"    Source: >KIWI 7.02
.\"  Language: English
.\"
.TH "KIWI::KIWIRC" "1" "Created: 06/29/2015" ">KIWI 7\&.02" "KIWI Manualpage"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
KIWI::kiwirc \- Resource file for the Kiwi imaging system
.SH "DESCRIPTION"
.PP
The KIWI imaging toolchain supports the use of an optional resource file named
\&.kiwirc
located in the users home directory\&.
.PP
The file is sourced by a Perl process and thus Perl compatible syntax for the supported variable settings is required\&.
.PP
\fBExample\ \&1.\ \&Template for .kiwi.rc\fR
.sp
.if n \{\
.RS 4
.\}
.nf
$BasePath=\*(Aq/usr/share/kiwi\*(Aq;
$Gzip=\*(Aqbzip2\*(Aq;
$LogServerPort=\*(Aq4455\*(Aq;
$System=\*(Aq/usr/share/kiwi/image\*(Aq;
.fi
.if n \{\
.RE
.\}
.SH "SUPPORTED RESOURCE SETTINGS"
.PP
KIWI recognizes the BasePath, Gzip, LogServerPort, LuksCipher, and System settings in the
\&.kiwirc
file\&.
.PP
[BasePath]
.RS 4
Path to the location of the KIWI image system components, such as modules, tests, image descriptions etc\&.
.sp
The default value is
/usr/share/kiwi
.RE
.PP
[Gzip]
.RS 4
Specify the compression utility to be used for various compression tasks during image generation\&.
.sp
The default value is
\fBgzip\fR\fB\-9\fR
.RE
.PP
[LogServerPort]
.RS 4
Specify a port number for log message queuing\&.
.sp
The default value is off
.RE
.PP
[LuksCipher]
.RS 4
Specify the cipher for the encrypted Luks filesystem\&.
.RE
.PP
[System]
.RS 4
Specify the location of the KIWI system image description\&.
.sp
The default value is the value of BasePath concatenated with /image\&.
.RE
.SH "AUTHOR"
.PP
\fBRobert Schweikert\fR <\&rschweikert (AT) novell\&.com\&>
.RS 4
Developer
.RE
