'\" t
.\"     Title: kiwi::config.sh
.\"    Author: Marcus Schäfer <ms (AT) suse.de>
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: Created: 06/29/2015
.\"    Manual: KIWI Manualpage
.\"    Source: KIWI 7.02
.\"  Language: English
.\"
.TH "KIWI::CONFIG\&.SH" "1" "Created: 06/29/2015" "KIWI 7\&.02" "KIWI Manualpage"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
KIWI::config.sh \- Customization File for KIWI image description
.SH "DESCRIPTION"
.PP
The KIWI image description allows to have an optional
config\&.sh
bash script in place\&. It can be used for changes appropriate for all images to be created from a given unpacked image (since config\&.sh runs prior to create step) Basically the script should be designed to take over control of adding the image operating system configuration\&. Configuration in that sense means all tasks which runs once in an os installation process like activating services, creating configuration files, prepare an environment for a firstboot workflow, etc\&. The
config\&.sh
script is called
\fIafter\fR
the following kiwi built in configuration tasks: User/Groups, copy of overlay root tree and setup of autoyast If
config\&.sh
exits with an exit code != 0 the kiwi process will exit with an error too\&.
.PP
\fBExample\ \&1.\ \&Template for config.sh\fR
.sp
.if n \{\
.RS 4
.\}
.nf
#======================================
# Functions\&.\&.\&.
#\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
test \-f /\&.kconfig && \&. /\&.kconfig
test \-f /\&.profile && \&. /\&.profile

#======================================
# Greeting\&.\&.\&.
#\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
echo "Configure image: [$kiwi_iname]\&.\&.\&."

#======================================
# Mount system filesystems
#\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
baseMount

#======================================
# Call configuration code/functions
#\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
\&.\&.\&.

#======================================
# Umount kernel filesystems
#\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
baseCleanMount

#======================================
# Exit safely
#\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
exit 0
.fi
.if n \{\
.RE
.\}
.SH "COMMON FUNCTIONS"
.PP
The
\&.kconfig
file allows to make use of a common set of functions\&. Functions specific to SUSE Linux specific begin with the name
\fIsuse\fR\&. Functions applicable to all linux systems starts with the name
\fIbase\fR\&. The following list describes the functions available inside the
config\&.sh
script\&.
.PP
[baseCleanMount]
.RS 4
Umount the system filesystems
/proc,
/dev/pts, and
/sys\&.
.RE
.PP
[baseDisableCtrlAltDel]
.RS 4
Disable the
Ctrl-Alt-Del
key sequence setting in
/etc/inittab
.RE
.PP
[baseGetPackagesForDeletion]
.RS 4
Return the name(s) of packages which will be deleted
.RE
.PP
[baseGetProfilesUsed]
.RS 4
Return the name(s) of profiles used to build this image
.RE
.PP
[baseSetRunlevel {value}]
.RS 4
Set the default run level
.RE
.PP
[baseSetupBoot]
.RS 4
Set up the linuxrc as init
.RE
.PP
[baseSetupBusyBox {\-f}]
.RS 4
activates busybox if installed for all links from the
busybox/busybox\&.links
file\(emyou can choose custom apps to be forced into busybox with the
\fB\-f\fR
option as first parameter, for example:
.sp
.if n \{\
.RS 4
.\}
.nf
baseSetupBusyBox \-f /bin/zcat /bin/vi
.fi
.if n \{\
.RE
.\}
.RE
.PP
[baseSetupInPlaceGITRepository]
.RS 4
Create an in place git repository of the root directory\&. This process may take some time and you may expect problems with binary data handling
.RE
.PP
[baseSetupInPlaceSVNRepository {path_list}]
.RS 4
Create an in place subversion repository for the specified directories\&. A standard call could look like this baseSetupInPlaceSVNRepository
/etc,
/srv, and
/var/log
.RE
.PP
[baseSetupPlainTextGITRepository]
.RS 4
Create an in place git repository of the root directory containing all plain/text files\&.
.RE
.PP
[baseSetupUserPermissions]
.RS 4
Search all home directories of all users listed in
/etc/passwd
and change the ownership of all files to belong to the correct user and group\&.
.RE
.PP
[baseStripAndKeep {list of info\-files to keep}]
.RS 4
helper function for strip* functions read stdin lines of files to check for removing params: files which should be keep
.RE
.PP
[baseStripDocs {list of docu names to keep}]
.RS 4
remove all documentation, except one given as parameter
.RE
.PP
[baseStripInfos {list of info\-files to keep}]
.RS 4
remove all info files, except one given as parameter
.RE
.PP
[baseStripLocales {list of locales}]
.RS 4
remove all locales, except one given as parameter
.RE
.PP
[baseStripMans {list of manpages to keep}]
.RS 4
remove all manual pages, except one given as parameter example: baseStripMans more less
.RE
.PP
[baseStripRPM]
.RS 4
remove rpms defined in
config\&.xml
in the image type=delete section
.RE
.PP
[suseRemovePackagesMarkedForDeletion]
.RS 4
remove rpms defined in
config\&.xml
in the image type=delete section\&. The difference compared to baseStripRPM is that the suse variant checks if the package is really installed prior to passing it to rpm to uninstall it\&. The suse rpm exits with an error exit code while there are other rpm version which just ignore if an uninstall request was set on a package which is not installed
.RE
.PP
[baseStripTools {list of toolpath} {list of tools}]
.RS 4
helper function for suseStripInitrd function params: toolpath, tools
.RE
.PP
[baseStripUnusedLibs]
.RS 4
remove libraries which are not directly linked against applications in the bin directories
.RE
.PP
[baseUpdateSysConfig {filename} {variable} {value}]
.RS 4
update sysconfig variable contents
.RE
.PP
[Debug {message}]
.RS 4
Helper function to print a message if the variable
\fIDEBUG\fR
is set to 1
.RE
.PP
[Echo {echo commandline}]
.RS 4
Helper function to print a message to the controlling terminal
.RE
.PP
[Rm {list of files}]
.RS 4
Helper function to delete files and announce it to log
.RE
.PP
[Rpm {rpm commandline}]
.RS 4
Helper function to the RPM function and announce it to log
.RE
.PP
[suseConfig]
.RS 4
Setup keytable language, timezone and hwclock if specified in
config\&.xml
and call SuSEconfig afterwards SuSEconfig is only called on systems which still support it
.RE
.PP
[suseInsertService {servicename}]
.RS 4
This function calls baseInsertService and exists only for compatibility reasons
.RE
.PP
[suseRemoveService {servicename}]
.RS 4
This function calls baseRemoveService and exists only for compatibility reasons
.RE
.PP
[baseInsertService {servicename}]
.RS 4
Activate the given service by using the chkconfig or systemctl program\&. Which init system is in use is auto detected
.RE
.PP
[baseRemoveService {servicename}]
.RS 4
Deactive the given service by using the chkconfig or systemctl program\&. Which init system is in use is auto detected
.RE
.PP
[baseService {servicename} {on|off}]
.RS 4
Activate/Deactivate a service by using the chkconfig or systemctl program\&. The function requires the service name and the value on or off as parameters\&. Which init system is in use is auto detected
.RE
.PP
[suseActivateDefaultServices]
.RS 4
Activates the following sysVInit services to be on by default using the chkconfig program: boot\&.rootfsck, boot\&.cleanup, boot\&.localfs, boot\&.localnet, boot\&.clock, policykitd, dbus, consolekit, haldaemon, network, atd, syslog, cron, kbd\&. And the following for systemd systems: network, cron
.RE
.PP
[suseSetupProduct]
.RS 4
This function creates the baseproduct link in /etc/products\&.d pointing to the installed product
.RE
.PP
[suseSetupProductInformation]
.RS 4
This function will use zypper to search for the installed product and install all product specific packages\&. This function only makes sense if zypper is used as packagemanager
.RE
.PP
[suseStripPackager {\-a}]
.RS 4
Remove smart or zypper packages and db files Also remove rpm package and db if
\fB\-a\fR
given
.RE
.SH "PROFILE ENVIRONMENT VARIABLES"
.PP
The \&.profile environment file contains a specific set of variables which are listed below\&. Some of the functions above makes use of the variables\&.
.PP
[$kiwi_compressed]
.RS 4
The value of the compressed attribute set in the type element in
config\&.xml
.RE
.PP
[$kiwi_delete]
.RS 4
A list of all packages which are part of the packages section with
type="delete" in
config\&.xml
.RE
.PP
[$kiwi_drivers]
.RS 4
A comma separated list of the driver entries as listed in the drivers section of the
config\&.xml\&.
.RE
.PP
[$kiwi_iname]
.RS 4
The name of the image as listed in
config\&.xml
.RE
.PP
[$kiwi_iversion]
.RS 4
The image version string major\&.minor\&.release
.RE
.PP
[$kiwi_keytable]
.RS 4
The contents of the keytable setup as done in
config\&.xml
.RE
.PP
[$kiwi_language]
.RS 4
The contents of the locale setup as done in
config\&.xml
.RE
.PP
[$kiwi_profiles]
.RS 4
A list of profiles used to build this image
.RE
.PP
[$kiwi_size]
.RS 4
The predefined size value for this image\&. This is not the computed size but only the optional size value of the preferences section in
config\&.xml
.RE
.PP
[$kiwi_timezone]
.RS 4
The contents of the timezone setup as done in
config\&.xml
.RE
.PP
[$kiwi_type]
.RS 4
The basic image type\&. Can be a simply filesystem image type of ext2, ext3, reiserfs, squashfs, cpio, or one of the following complex image types: iso, split, usb, vmx, oem, xen, or pxe\&.
.RE
.SH "AUTHOR"
.PP
\fBMarcus Schäfer\fR <\&ms (AT) suse\&.de\&>
.RS 4
Developer
.RE
