#!/bin/bash
#================
# FILE          : preinit
#----------------
# PROJECT       : OpenSuSE KIWI Image System
# COPYRIGHT     : (c) 2006 SUSE LINUX Products GmbH. All rights reserved
#               :
# AUTHOR        : Marcus Schaefer <ms@suse.de>
#               :
# BELONGS TO    : Operating System images
#               :
# DESCRIPTION   : This file is called after the image root
#               : has changed by the linuxrc script
#               :
# STATUS        : BETA
#----------------
#======================================
# Functions...
#--------------------------------------
. /include

#======================================
# 1) start error log
#--------------------------------------
Echo "Calling pre-init stage in system image"
errorLogStart

#======================================
# 2) check for LOCAL_BOOT
#--------------------------------------
if [ $LOCAL_BOOT = "yes" ];then
	exit 0
fi

#======================================
# 3) update mount table
#--------------------------------------
updateMTAB

#======================================
# 4) create framebuffer devices
#--------------------------------------
createFramebufferDevices

#======================================
# 5) create initrd on diskful
#--------------------------------------
if [ -z "$UNIONFS_CONFIG" ] && [ -z "$COMBINED_IMAGE" ]; then
	#======================================
	# use distro initrd via mkinitrd
	#--------------------------------------
	setupSUSEInitrd
else
	#======================================
	# use kiwi initrd from boot partition
	#--------------------------------------
	mount -t proc  proc  /proc >/dev/null
	mount -t sysfs sysfs /sys  >/dev/null
	probeFileSystem $deviceBoot
	if [ ! "$FSTYPE" = "unknown" ];then
		modprobe $FSTYPE
	fi
	if mount $deviceBoot /kiwiboot;then
		rm -rf /boot && ln -s /kiwiboot/boot /boot
		pushd /boot &>/dev/null
		rm -f vmlinuz && ln -s linux.vmx  vmlinuz
		rm -f initrd  && ln -s initrd.vmx initrd
		popd &>/dev/null
		kernelList
		if [ ! -z "$COMBINED_IMAGE" ];then
			Echo "Creating grub configuration for split system"
		else
			Echo "Creating grub configuration for unified system"
		fi
		setupBootLoaderGrub / / 0 ${deviceDisk}2 OEM $deviceSwap
		grubOK=1
	else
		Echo "Failed to mount boot partition"
		Echo "Can't create grub configuration"
		grubOK=0
	fi
	umount /proc >/dev/null
	umount /sys  >/dev/null
fi

#======================================
# 6) Install boot loader if ok
#--------------------------------------
if [ $grubOK = 1 ];then
	installBootLoaderGrub
	if [ -d /kiwiboot ];then
		umount -l $deviceBoot &>/dev/null
	fi
fi

#======================================
# 7) create /etc/ImagePackages
#--------------------------------------
if [ -x /bin/rpm ];then
	Echo "Creating initial image package info file"
	rpm -qa --last > /etc/ImagePackages
fi
