#!/bin/bash

if [ ! $UID = 0 ];then
	echo "$0: needs root privileges... abort"
	exit 1
fi

kiwi --root $HOME/mydvd --prepare /usr/share/kiwi/image/kwliveCD-suse-10.3 && \
kiwi --create $HOME/mydvd -d $HOME

file=`ls -1 $HOME/openSUSE-10.3*.iso`
echo "ISO image created: $file"
