#!/usr/bin/perl

use strict;
use Env;

#==========================================
# extractFile
#------------------------------------------
sub extractFile {
	# ...
	# extract files from an RPM to a given
	# destination directory
	# ---
	my $package = shift;
	my $dest    = shift;
	my @opts = qw (
		--extract
		--unconditional
		--preserve-modification-time
		--make-directories
		--quiet
		# EOF
	);
	qx (cd $dest && rpm2cpio $package | cpio @opts);
}

#==========================================
# main
#------------------------------------------
sub main {
	my $source = $ARGV[0];
	if (! -d $source) {
		exit 1;
	}
	my @packages = glob ("$source/*.rpm");
	foreach my $package (@packages) {
		extractFile ($package,$source);
	}
	exit 0;
}

main();
