#!/bin/bash

set -x
#==========================================
# Set variables
#------------------------------------------
bootfs=$1
file=boot/config.txt

#==========================================
# Check for berryboot config.txt
#------------------------------------------
echo 'disable_overscan=1' >> $file

