#!/bin/bash     

set -x
#==========================================
# Set variables
#------------------------------------------
bootfs=$1
file=boot/boot.script

#==========================================
# Check for berryboot config.txt
#------------------------------------------
if [ -f "boot/config.txt" ];then
	file=boot/config.txt
	echo 'disable_overscan=1' >> $file
	exit 0
fi

#==========================================
# Create default boot script
#------------------------------------------
echo 'printenv kerneladdr || setenv kerneladdr ${kernel_addr_r}'   >> $file
echo 'printenv ramdiskaddr|| setenv ramdiskaddr ${ramdisk_addr_r}' >> $file
echo -n 'setenv bootcmd "'                                         >> $file
if [[ $bootfs =~ fat ]];then
	echo -n 'fatload mmc 0:1 ${kerneladdr} boot/linux.vmx; '       >> $file
	echo -n 'fatload mmc 0:1 ${ramdiskaddr} boot/initrd.uboot; '   >> $file
else
	echo -n 'ext2load mmc 0:1 ${kerneladdr} boot/linux.vmx; '      >> $file
	echo -n 'ext2load mmc 0:1 ${ramdiskaddr} boot/initrd.uboot; '  >> $file
fi
echo 'bootm ${kerneladdr} ${ramdiskaddr}";'                        >> $file
echo 'boot'                                                        >> $file

#==========================================
# Create machine readable uboot format
#------------------------------------------
mkopts="-A arm -O linux -a 0 -e 0 -T script -C none";
inputf="boot/boot.script";
result="boot/boot.scr";
if ! mkimage $mkopts -n 'Boot-Script' -d $inputf $result;then
	echo "Failed to create uboot script image"
	exit 1
fi

